version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skilldb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend  # Assuming your backend Dockerfile and code are in ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/skilldb"
      JWT_SECRET: "mysecret362lax@"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend  # Assuming your frontend Dockerfile and code are in ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: yarn dev --host
    environment:
      VITE_API_URL: "http://localhost:5000/api" # Adjust if needed

volumes:
  mysql_data:
