version: "3.8"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skilldb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # backend:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     DATABASE_URL: "mysql://root:root@db:3306/skilldb"
  #     JWT_SECRET: "supersecretkey"
  #     PORT: 5000
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db

volumes:
  mysql_data:
